# Generated by Django 4.2.3 on 2024-01-24 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('animal', models.CharField(max_length=30)),
                ('city', models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('BIRD', 'Bird'), ('HORSE', 'Horse')], max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('goal', models.IntegerField()),
                ('image', models.URLField()),
                ('is_open', models.BooleanField()),
                ('is_successful', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2024, 1, 24, 12, 50, 59, 203472))),
                ('deadline', models.DateTimeField(default=projects.models.one_month_from_today)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.project')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_pledges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
