# Generated by Django 4.2.3 on 2024-01-28 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='animal',
            field=models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('BIRD', 'Bird'), ('HORSE', 'Horse')], max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 9, 17, 45, 650251)),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
