# Generated by Django 4.2.3 on 2024-01-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_pledge_supporter_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='animal',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='breed',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
