# Generated by Django 4.2.3 on 2024-01-29 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_pledge_anonymous_alter_project_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 9, 3, 34, 855612)),
        ),
    ]
