# Generated by Django 4.2.3 on 2024-01-23 05:48

import datetime
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_animal_project_breed_project_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='breed',
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=projects.models.one_month_from_today),
        ),
        migrations.AddField(
            model_name='project',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('BIRD', 'Bird'), ('HORSE', 'Horse')], default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 5, 48, 26, 992604)),
        ),
    ]
