# Generated by Django 4.2.3 on 2024-03-05 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 14, 15, 23, 806812)),
        ),
    ]
